version: '3'

services:
  books:
    image: ghcr.io/pglaum/pglaum.de:main
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - swarm-proxy

networks:
  swarm-proxy:
    external: true
