version: '3'

services:
  books:
    image: ghcr.io/pglaum/books:main
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    networks:
      - swarm-proxy

networks:
  swarm-proxy:
    external: true
